//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hentry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class main_database : DbContext
    {
        public main_database()
            : base("name=main_database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<approver> approver { get; set; }
        public virtual DbSet<assignee> assignee { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<projectmanager> projectmanager { get; set; }
        public virtual DbSet<projectworker> projectworker { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
