//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hentry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.assignee = new HashSet<assignee>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int creator { get; set; }
        public int project { get; set; }
        public int status { get; set; }
        public Nullable<long> estimate_work { get; set; }
        public Nullable<long> estimate_cost { get; set; }
        public Nullable<long> actual_work { get; set; }
        public Nullable<long> actual_cost { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignee> assignee { get; set; }
        public virtual project project1 { get; set; }
        public virtual status status1 { get; set; }
        public virtual user user { get; set; }
    }
}
